// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsH1ifUGtzsa8sAC6NnBwlWXDkLReuO_4',
    appId: '1:746531469350:web:4ded6e2fc9b67e167c0ee7',
    messagingSenderId: '746531469350',
    projectId: 'exfai-6ad01',
    authDomain: 'exfai-6ad01.firebaseapp.com',
    storageBucket: 'exfai-6ad01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNgWiDQKSr631H_HUaMAIGEthXlFNN3qo',
    appId: '1:746531469350:android:27bf4c01741bd6517c0ee7',
    messagingSenderId: '746531469350',
    projectId: 'exfai-6ad01',
    storageBucket: 'exfai-6ad01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3QGLsPmYMC7uYCqggOeajPiCaZUu0mw',
    appId: '1:746531469350:ios:b911ba77ebce97a77c0ee7',
    messagingSenderId: '746531469350',
    projectId: 'exfai-6ad01',
    storageBucket: 'exfai-6ad01.appspot.com',
    androidClientId: '746531469350-j8qems1vk6ctsn5v4du4sb091v0tobtv.apps.googleusercontent.com',
    iosClientId: '746531469350-lq6g610p4u6iqmr28lsd93lobb4qo64j.apps.googleusercontent.com',
    iosBundleId: 'com.exfai.exfai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm3QGLsPmYMC7uYCqggOeajPiCaZUu0mw',
    appId: '1:746531469350:ios:b911ba77ebce97a77c0ee7',
    messagingSenderId: '746531469350',
    projectId: 'exfai-6ad01',
    storageBucket: 'exfai-6ad01.appspot.com',
    androidClientId: '746531469350-j8qems1vk6ctsn5v4du4sb091v0tobtv.apps.googleusercontent.com',
    iosClientId: '746531469350-lq6g610p4u6iqmr28lsd93lobb4qo64j.apps.googleusercontent.com',
    iosBundleId: 'com.exfai.exfai',
  );
}
